

/*CREAR UN TRIGGER TAL QUE CUANDO SE CREE UNA CITA SE INSERTE UNA FILA A PRODUCTO_USADO
Y SE DISMINUYA EL STOCK DEL PRODUCTO EN LA TABLA PRODUCTO (REVISAR AdminCitas)*/
DELIMITER $$

CREATE TRIGGER tr_producto_disminuir
AFTER INSERT ON producto_usado
FOR EACH ROW
BEGIN
    UPDATE producto
    SET stock = stock - NEW.cantidad
    WHERE id_producto = NEW.producto;
END$$

DELIMITER ;



/*CREAR UN TRIGGER TAL QUE CUANDO SE ELIMINE UNA CITA SE ELIMINE UNA FILA DE PRODUCTO_USADO
Y SE AUMENTE (SE DEVUELVA) EL STOCK DEL PRODUCTO EN LA TABLA PRODUCTO (REVISAR AdminCitas)*/
DELIMITER $$

CREATE TRIGGER tr_producto_aumentar
AFTER DELETE ON producto_usado
FOR EACH ROW
BEGIN
    UPDATE producto
    SET stock = stock + OLD.cantidad
    WHERE id_producto = OLD.id_producto;
END$$

DELIMITER ;
