USE  LUBRICONTROL;

/*CREAR UN TRIGGER TAL QUE CUANDO SE CREE UNA CITA SE INSERTE UNA FILA A PRODUCTO_USADO
Y SE DISMINUYA EL STOCK DEL PRODUCTO EN LA TABLA PRODUCTO (REVISAR AdminCitas)*/

/*CREAR UN TRIGGER TAL QUE CUANDO SE ELIMINE UNA CITA SE ELIMINE UNA FILA DE PRODUCTO_USADO
Y SE AUMENTE (SE DEVUELVA) EL STOCK DEL PRODUCTO EN LA TABLA PRODUCTO (REVISAR AdminCitas)*/